import auth from "@react-native-firebase/auth";

import { IPlant, IUserPlant } from "@/constants/IPlant";
import saveBasePlantToFirebase from "@/helpers/firebase/saveToFirebase/saveBasePlantToFirebase";
import saveUserPlantToFirebase from "@/helpers/firebase/saveToFirebase/saveUserPlantToFirebase";

export type SeedOptions = {
  /** Max base plants to seed; defaults to 8 */
  baseLimit?: number;
  /** Max user plants to seed; defaults to 8 */
  userLimit?: number;
};

const basePlants: IPlant[] = [
  {
    id: "monstera-deliciosa",
    name: "Monstera Deliciosa",
    slug: "monstera deliciosa",
    watering_frequency: 7,
    sun_requirements: "Bright indirect",
    humidity_requirements: "High",
    growth_rate: "Moderate",
    description: "Classic Swiss cheese plant; prefers evenly moist soil.",
    contributedBy: "seed-script",
    isVerified: false,
  },
  {
    id: "sansevieria-trifasciata",
    name: "Snake Plant",
    slug: "snake plant",
    watering_frequency: 14,
    sun_requirements: "Low to bright indirect",
    growth_rate: "Slow",
    description: "Drought tolerant; let soil dry between waterings.",
    contributedBy: "seed-script",
    isVerified: false,
  },
  {
    id: "epipremnum-aureum",
    name: "Golden Pothos",
    slug: "pothos",
    watering_frequency: 6,
    sun_requirements: "Low to medium indirect",
    growth_rate: "Fast",
    description: "Forgiving vining plant; likes light moisture.",
    contributedBy: "seed-script",
    isVerified: false,
  },
  {
    id: "spathiphyllum-wallisii",
    name: "Peace Lily",
    slug: "peace lily",
    watering_frequency: 4,
    sun_requirements: "Low to medium indirect",
    humidity_requirements: "Medium-high",
    growth_rate: "Moderate",
    description: "Prefers consistently damp (not soggy) soil.",
    contributedBy: "seed-script",
    isVerified: false,
  },
  {
    id: "zamioculcas-zamiifolia",
    name: "ZZ Plant",
    slug: "zz plant",
    watering_frequency: 10,
    sun_requirements: "Low to bright indirect",
    growth_rate: "Slow",
    description: "Thick rhizomes store water; avoid overwatering.",
    contributedBy: "seed-script",
    isVerified: false,
  },
  {
    id: "aloe-vera",
    name: "Aloe Vera",
    slug: "aloe vera",
    watering_frequency: 14,
    sun_requirements: "Bright direct to bright indirect",
    growth_rate: "Moderate",
    description: "Succulent; let pot fully dry between drinks.",
    contributedBy: "seed-script",
    isVerified: false,
  },
  {
    id: "chlorophytum-comosum",
    name: "Spider Plant",
    slug: "spider plant",
    watering_frequency: 6,
    sun_requirements: "Medium indirect",
    growth_rate: "Fast",
    description: "Likes lightly moist soil; avoid soggy roots.",
    contributedBy: "seed-script",
    isVerified: false,
  },
  {
    id: "ficus-lyrata",
    name: "Fiddle Leaf Fig",
    slug: "fiddle leaf fig",
    watering_frequency: 7,
    sun_requirements: "Bright indirect",
    growth_rate: "Moderate",
    description: "Let top inch dry, then water thoroughly.",
    contributedBy: "seed-script",
    isVerified: false,
  },
  {
    id: "ficus-elastica",
    name: "Rubber Plant",
    slug: "rubber plant",
    watering_frequency: 7,
    sun_requirements: "Bright indirect",
    growth_rate: "Moderate",
    description: "Thick leaves; allow top soil to dry between waterings.",
    contributedBy: "seed-script",
    isVerified: false,
  },
  {
    id: "philodendron-hederaceum-brasil",
    name: "Philodendron Brasil",
    slug: "philodendron brasil",
    watering_frequency: 5,
    sun_requirements: "Medium indirect",
    growth_rate: "Fast",
    description: "Variegated trailing philodendron; likes light moisture.",
    contributedBy: "seed-script",
    isVerified: false,
  },
  {
    id: "calathea-ornata",
    name: "Calathea Ornata",
    slug: "calathea ornata",
    watering_frequency: 4,
    sun_requirements: "Low to medium indirect",
    humidity_requirements: "High",
    growth_rate: "Moderate",
    description: "Prayer plant with pink stripes; keep evenly moist.",
    contributedBy: "seed-script",
    isVerified: false,
  },
  {
    id: "dracaena-marginata",
    name: "Dracaena Marginata",
    slug: "dracaena marginata",
    watering_frequency: 9,
    sun_requirements: "Medium indirect",
    growth_rate: "Slow",
    description: "Allow soil to dry partially; avoid overwatering.",
    contributedBy: "seed-script",
    isVerified: false,
  },
  {
    id: "aglaonema-maria",
    name: "Chinese Evergreen (Maria)",
    slug: "chinese evergreen",
    watering_frequency: 8,
    sun_requirements: "Low to medium indirect",
    growth_rate: "Moderate",
    description: "Tolerant of lower light; keep lightly moist.",
    contributedBy: "seed-script",
    isVerified: false,
  },
  {
    id: "hedera-helix",
    name: "English Ivy",
    slug: "english ivy",
    watering_frequency: 5,
    sun_requirements: "Medium indirect",
    growth_rate: "Fast",
    description: "Keep soil slightly moist; enjoys cooler temps.",
    contributedBy: "seed-script",
    isVerified: false,
  },
  {
    id: "pilea-peperomioides",
    name: "Pilea (Chinese Money Plant)",
    slug: "pilea",
    watering_frequency: 6,
    sun_requirements: "Bright indirect",
    growth_rate: "Moderate",
    description: "Water when top inch is dry; rotate for even growth.",
    contributedBy: "seed-script",
    isVerified: false,
  },
  {
    id: "schefflera-arboricola",
    name: "Umbrella Plant",
    slug: "umbrella plant",
    watering_frequency: 7,
    sun_requirements: "Bright indirect",
    growth_rate: "Moderate",
    description: "Let soil dry slightly; avoid soggy roots.",
    contributedBy: "seed-script",
    isVerified: false,
  },
  {
    id: "nephrolepis-exaltata",
    name: "Boston Fern",
    slug: "boston fern",
    watering_frequency: 3,
    sun_requirements: "Medium indirect",
    humidity_requirements: "High",
    growth_rate: "Fast",
    description: "Keep consistently moist and humid for best fronds.",
    contributedBy: "seed-script",
    isVerified: false,
  },
  {
    id: "peperomia-obtusifolia",
    name: "Peperomia (Baby Rubber)",
    slug: "peperomia",
    watering_frequency: 7,
    sun_requirements: "Medium indirect",
    growth_rate: "Slow",
    description: "Thick leaves store water; let top soil dry.",
    contributedBy: "seed-script",
    isVerified: false,
  },
  {
    id: "syngonium-podophyllum",
    name: "Arrowhead Vine",
    slug: "syngonium",
    watering_frequency: 5,
    sun_requirements: "Medium indirect",
    growth_rate: "Fast",
    description: "Water when top inch dries; appreciates humidity.",
    contributedBy: "seed-script",
    isVerified: false,
  },
];

const buildUserPlants = (userId: string): IUserPlant[] => [
  {
    id: "seed-up-1",
    userId,
    plantId: "monstera-deliciosa",
    custom_name: "Office Monstera",
    custom_watering_schedule: 7,
    last_watered_date: new Date("2025-12-14T10:00:00.000Z").getTime(),
    next_watering_date: new Date("2025-12-21T10:00:00.000Z").getTime(),
    location: "Office window",
    is_favorite: true,
  },
  {
    id: "seed-up-2",
    userId,
    plantId: "sansevieria-trifasciata",
    custom_name: "Bedroom Snake Plant",
    custom_watering_schedule: 14,
    last_watered_date: new Date("2025-12-10T10:00:00.000Z").getTime(),
    next_watering_date: new Date("2025-12-24T10:00:00.000Z").getTime(),
    location: "Bedroom dresser",
  },
  {
    id: "seed-up-3",
    userId,
    plantId: "spathiphyllum-wallisii",
    custom_name: "Lobby Peace Lily",
    custom_watering_schedule: 3,
    last_watered_date: new Date("2025-12-17T08:00:00.000Z").getTime(),
    next_watering_date: new Date("2025-12-20T08:00:00.000Z").getTime(),
    location: "Lobby shelf",
  },
  {
    id: "seed-up-4",
    userId,
    plantId: "epipremnum-aureum",
    custom_name: "Kitchen Pothos",
    custom_watering_schedule: 6,
    last_watered_date: new Date("2025-12-18T09:00:00.000Z").getTime(),
    next_watering_date: new Date("2025-12-24T09:00:00.000Z").getTime(),
    location: "Kitchen shelf",
    is_favorite: true,
  },
  {
    id: "seed-up-5",
    userId,
    plantId: "zamioculcas-zamiifolia",
    custom_name: "Lobby ZZ",
    custom_watering_schedule: 10,
    last_watered_date: new Date("2025-12-05T12:00:00.000Z").getTime(),
    next_watering_date: new Date("2025-12-15T12:00:00.000Z").getTime(),
    location: "Lobby corner",
  },
  {
    id: "seed-up-6",
    userId,
    plantId: "aloe-vera",
    custom_name: "Sunny Aloe",
    custom_watering_schedule: 14,
    last_watered_date: new Date("2025-12-01T11:00:00.000Z").getTime(),
    next_watering_date: new Date("2025-12-15T11:00:00.000Z").getTime(),
    location: "South windowsill",
  },
  {
    id: "seed-up-7",
    userId,
    plantId: "chlorophytum-comosum",
    custom_name: "Hall Spider Plant",
    custom_watering_schedule: 6,
    last_watered_date: new Date("2025-12-16T15:00:00.000Z").getTime(),
    next_watering_date: new Date("2025-12-22T15:00:00.000Z").getTime(),
    location: "Hallway shelf",
  },
  {
    id: "seed-up-8",
    userId,
    plantId: "ficus-lyrata",
    custom_name: "Living Room Fiddle",
    custom_watering_schedule: 7,
    last_watered_date: new Date("2025-12-12T09:30:00.000Z").getTime(),
    next_watering_date: new Date("2025-12-19T09:30:00.000Z").getTime(),
    location: "Living room",
  },
  {
    id: "seed-up-9",
    userId,
    plantId: "ficus-elastica",
    custom_name: "Office Rubber Plant",
    custom_watering_schedule: 7,
    last_watered_date: new Date("2025-12-07T10:00:00.000Z").getTime(),
    next_watering_date: new Date("2025-12-14T10:00:00.000Z").getTime(),
    location: "Office corner",
  },
  {
    id: "seed-up-10",
    userId,
    plantId: "philodendron-hederaceum-brasil",
    custom_name: "Desk Brasil",
    custom_watering_schedule: 5,
    last_watered_date: new Date("2025-12-19T07:00:00.000Z").getTime(),
    next_watering_date: new Date("2025-12-24T07:00:00.000Z").getTime(),
    location: "Work desk",
    is_favorite: true,
  },
  {
    id: "seed-up-11",
    userId,
    plantId: "calathea-ornata",
    custom_name: "Ornata Shelf",
    custom_watering_schedule: 4,
    last_watered_date: new Date("2025-12-18T18:00:00.000Z").getTime(),
    next_watering_date: new Date("2025-12-22T18:00:00.000Z").getTime(),
    location: "Bookshelf",
  },
  {
    id: "seed-up-12",
    userId,
    plantId: "dracaena-marginata",
    custom_name: "Marginata Entry",
    custom_watering_schedule: 9,
    last_watered_date: new Date("2025-12-03T13:00:00.000Z").getTime(),
    next_watering_date: new Date("2025-12-12T13:00:00.000Z").getTime(),
    location: "Entryway",
  },
  {
    id: "seed-up-13",
    userId,
    plantId: "aglaonema-maria",
    custom_name: "Evergreen Corner",
    custom_watering_schedule: 8,
    last_watered_date: new Date("2025-12-11T08:00:00.000Z").getTime(),
    next_watering_date: new Date("2025-12-19T08:00:00.000Z").getTime(),
    location: "Bedroom corner",
  },
  {
    id: "seed-up-14",
    userId,
    plantId: "hedera-helix",
    custom_name: "Ivy Mantle",
    custom_watering_schedule: 5,
    last_watered_date: new Date("2025-12-09T09:00:00.000Z").getTime(),
    next_watering_date: new Date("2025-12-14T09:00:00.000Z").getTime(),
    location: "Fireplace mantle",
  },
  {
    id: "seed-up-15",
    userId,
    plantId: "pilea-peperomioides",
    custom_name: "Pilea Stand",
    custom_watering_schedule: 6,
    last_watered_date: new Date("2025-12-13T16:00:00.000Z").getTime(),
    next_watering_date: new Date("2025-12-19T16:00:00.000Z").getTime(),
    location: "Plant stand",
  },
  {
    id: "seed-up-16",
    userId,
    plantId: "schefflera-arboricola",
    custom_name: "Umbrella Office",
    custom_watering_schedule: 7,
    last_watered_date: new Date("2025-12-08T10:00:00.000Z").getTime(),
    next_watering_date: new Date("2025-12-15T10:00:00.000Z").getTime(),
    location: "Office window",
  },
  {
    id: "seed-up-17",
    userId,
    plantId: "nephrolepis-exaltata",
    custom_name: "Boston Fern Bath",
    custom_watering_schedule: 3,
    last_watered_date: new Date("2025-12-19T10:00:00.000Z").getTime(),
    next_watering_date: new Date("2025-12-22T10:00:00.000Z").getTime(),
    location: "Bathroom shelf",
    is_favorite: true,
  },
  {
    id: "seed-up-18",
    userId,
    plantId: "peperomia-obtusifolia",
    custom_name: "Peperomia Desk",
    custom_watering_schedule: 7,
    last_watered_date: new Date("2025-12-06T12:00:00.000Z").getTime(),
    next_watering_date: new Date("2025-12-13T12:00:00.000Z").getTime(),
    location: "Home office",
  },
  {
    id: "seed-up-19",
    userId,
    plantId: "syngonium-podophyllum",
    custom_name: "Arrowhead Shelf",
    custom_watering_schedule: 5,
    last_watered_date: new Date("2025-12-17T09:00:00.000Z").getTime(),
    next_watering_date: new Date("2025-12-22T09:00:00.000Z").getTime(),
    location: "Living room shelf",
  },
];

export async function seedFakePlants(options: SeedOptions = {}) {
  const { baseLimit = 8, userLimit = 8 } = options;
  let user = auth().currentUser;

  if (!user) {
    try {
      const creds = await auth().signInAnonymously();
      user = creds.user;
    } catch (error) {
      console.warn("seedFakePlants: sign-in failed; ensure auth is configured.");
      throw error;
    }
  }

  const userPlants = buildUserPlants(user.uid).slice(0, Math.max(0, userLimit));

  for (const plant of basePlants.slice(0, Math.max(0, baseLimit))) {
    await saveBasePlantToFirebase(plant, user);
  }

  for (const plant of userPlants) {
    await saveUserPlantToFirebase(plant, user);
  }

  return true;
}

export default seedFakePlants;
